name: get_data
channels:
  - conda-forge
  - defaults
dependencies:
  - pip=20.3.3
  - requests=2.24.0
  - pandas=1.2.3
  - pip=20.3.3
  - pytest=6.2.2
  - scipy=1.5.2
  - pip:
      - wandb==0.10.31
      - git+https://github.com/udacity/nd0821-c2-build-model-workflow-starter.git#egg=wandb-utils&subdirectory=components